- name: Install build-essential, bash, and gcc
  pacman: name=build-essential state=installed
  pacman: name=bash state=installed
  pacman: name=gcc state=installed

- name: Install net-utils, dialog, openssh
  pacman: name=net-utils state=installed
  pacman: name=dialog state=installed
  pacman: name=openssh state=installed

- name: Install git
  pacman: name=git state=installed

- name: Install Arch's sudo implementation
  pacman: name=sudo state=installed

- name: Install alsa, jack, qjackctl, and alsa-utils
  pacman: name=alsa state=installed
  pacman: name=jack state=installed
  pacman: name=qjackctl state=installed
  pacman: name=alsa-utils state=installed

- name: Install tree
  pacman: name=tree state=installed

- name: Install the X Windowing System and startx
  pacman: name=xorg state=installed
  pacman: name=xorg-server state=installed
  pacman: name=xorg-xinit state=installed

- name: Install xmonad, dmenu, and xmobar
  pacman: name=xmonad state=installed
  pacman: name=dmenu state=installed
  pacman: name=xmobar state=installed

- name: Install fonts
  pacman: name=ttf-inconsolata state=installed
  pacman: name=ttf-sanazami state=installed
  pacman: name=ttf-symbola state=installed

- name: Install postgresql, mariadb, and redis
  pacman: name=postgresql state=installed
  pacman: name=mariadb state=installed
  pacman: name=redis state=installed